language: python
python:
  - "3.5"

cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt


services:
- postgresql

before_script:
  - psql -c 'create database online_compiler;' -U postgres
  - ./OnlineCompiler/manage.py migrate

script:
- OnlineCompiler/manage.py test compiler
- OnlineCompiler/manage.py test login
