language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: nosetests

services:
– postgresql

before_script:
  - psql -c 'create database online_compiler;' -U postgres
  - python manage.py syncdb –migrate –noinput

script:
- python manage.py test
